app:
  name: "Donut Backend"
  version: "0.0.1-dev"
  desc: "Shaping new gen change makers"
server:
  host: ""
db:
  url: ""
auth:
  jwt_secret: "donut-secret"
  google:
    client_id: ""
    client_secret: ""