name: Deploy Backend

on:
  push:
    branches: [ main ]
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          project_id: donut-app-337308
