name: Deploy Backend

on:
  push:
    branches: [ staging ]
  
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          cat > env.yaml << EOF
          env_variables:
            GOOGLE_OAUTH_CLIENT_ID: '${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}'
            GOOGLE_OAUTH_CLIENT_SECRET: '${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}'
          EOF
      - run: |
          cat > config.yaml << EOF
          app:
            name: "Donut Backend"
            version: "0.0.1-dev"
            desc: "Shaping new gen change makers"
          db:
            url: "${{ secrets.DB_URL }}"
          auth:
            jwt_secret: "${{ secrets.JWT_SECRET }}"
            google:
              client_id: "${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}"
              client_secret: "${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}"
          emailer:
            email: "${{ secrets.GMAIL }}"
            apppassword: "${{ secrets.GMAIL_APP_PASSWORD }}"
          EOF
      - run: |
          cat > app.yaml << EOF
          runtime: go116
          service: api
          handlers:
            - url: /.*
              script: auto
              secure: always
              redirect_http_response_code: 301
          includes: 
            - env.yaml
          EOF
      - run: |
          cat > .env << EOF
          PORT=37227
          GIN_MODE="debug"
          EOF
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          project_id: donut-366007
