name: Deploy Backend Staging

on:
  push:
    branches: [ staging ]
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          cat > config.yaml << EOF
          app:
            name: "Donut Backend"
            version: "0.0.1-dev"
            desc: "Shaping new gen change makers"
          db:
            url: "${{ secrets.DB_STAGING_URL }}"
            name: "${{ secrets.DB_STAGING_NAME }}"
          auth:
            jwt_secret: "${{ secrets.JWT_SECRET_STAGING }}"
            google:
              client_id: "${{ secrets.GOOGLE_OAUTH_CLIENT_ID_STAGING }}"
              client_secret: "${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET_STAGING }}"
          emailer:
            email: "${{ secrets.GMAIL_STAGING }}"
            apppassword: "${{ secrets.GMAIL_APP_PASSWORD_STAGING }}"
          cloud:
            userbucket : "${{ secrets.GCLOUD_BUCKET_STAGING }}"
          captcha:
            secret: "${{ secrets.RECAPTCHA_SITE_SECRET_STAGING }}"
          EOF
      - run: |
          cat > app.yaml << EOF
          runtime: go116
          service: staging-api
          handlers:
            - url: /.*
              script: auto
              secure: always
              redirect_http_response_code: 301
          EOF
      - run: |
          cat > .env << EOF
          PORT=37227
          GIN_MODE="release"
          ENV=prod
          EOF
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_KEY_STAGING }}'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          project_id: donut-366007